// SYS-W11-04 — corpus-driven libFuzzer harness over self-contained GLB
// import. The importer accepts bytes directly, so hostile inputs never need
// to be materialised as temporary files during fuzzing.

#include "GltfImporter.hpp"

#include <cstddef>
#include <cstdint>
#include <span>

extern "C" int LLVMFuzzerTestOneInput(const uint8_t* data, size_t size) {
    try {
        (void)mc3togltf::importSelfContainedGlbBytes(
            std::span<const unsigned char>(data, size), "fuzz-input.glb");
    } catch (const std::exception&) {
        // Parser/import rejection is expected for most generated bytes.
    }
    return 0;
}
